<a href="https://colab.research.google.com/github/upjun11/r/blob/main/09_26%EA%B3%BC%EC%A0%9C_%EA%B9%80%EA%B0%95%EC%9A%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1.Numpy Basics

### 1-01 배열 생성

In [ ]:
import numpy as np

In [ ]:
# 아래와 같은 1차원 배열을 생성하세요.
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
# 아래와 같이 2차원 배열을 생성하세요.
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
# 3차원 배열 생성
a=np.array([[[0,1,2,3],[4,5,6,7],[8,9,10,11]]])
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

#### 1-01-02 arange 함수


In [ ]:
# 0 ~ 9 값을 갖는 배열 생성하세요.
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 0.1 ~ 1.0 까지 0.1씩 증가는 값을 갖는 배열 생성
np.arange(0,1,0.1)


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#### 1-01-03 linspace 함수


In [ ]:
# 1 ~ 10 까지 3개의 값을 갖는 배열 생성하세요.
a=np.linspace(1,10,num=3)

#### 1-01-04 기타 배열 생성 함수

In [ ]:
# 1 값으로 채워진 2행 2열의 배열 생성


array([[1., 1.],
       [1., 1.]])

In [ ]:
# 0 값으로 채워진 2행 2열의 배열 생성
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
# -1 값으로 채워진 2행 2열의 배열 생성
# np.full(shape, value)  참고 함수
np.full((2,2),-1)

array([[-1, -1],
       [-1, -1]])

### 1-02 Numpy Array 속성


In [ ]:
# 빈 곳에 알맞은 속성 이름을 적어보세요.

In [ ]:
array = np.array([[1, 2], [3, 4]])
print('array의 차원:', array.ndim)


array의 차원: 2


In [ ]:
print('array의 각 차원별 크기:', array.shape)

array의 각 차원별 크기: (2, 2)


In [ ]:
print('array의 요소의 총 개수 :', array.size)

array의 요소의 총 개수 : 4


In [ ]:
print('array의 데이터 유형 :', array.dtype)    #int32, int64,  float32, float64

array의 데이터 유형 : int64


In [ ]:
print('array의 전치 (전) :')
print(array)
print('array의 전치 (후) :')
print(array.T)

array의 전치 (전) :
[[1 2]
 [3 4]]
array의 전치 (후) :
[[1 3]
 [2 4]]
