<a href="https://colab.research.google.com/github/upjun11/r/blob/main/%EA%B8%B0%EA%B3%84%ED%95%99%EC%8A%B5_%ED%8C%8C%EC%9D%B4%EC%8D%AC_5%EC%A3%BC%EC%B0%A8%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as pilt



* 스칼라 정의하기

In [ ]:
a=1
b=2
c=tf.math.add(a,b)
c

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
c.numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=int32, numpy=3>>

In [ ]:
c1=tf.constant(1)
c2=tf.constant(2)
print(c1,c2)

tf.Tensor(1, shape=(), dtype=int32) tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
f1=tf.cast(c1,tf.float32)
f2=tf.cast(c2,tf.float32)
print(c1,c2)

tf.Tensor(1, shape=(), dtype=int32) tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
##덧셈
add=tf.math.add(c1,c2)
add.numpy()
#.numpy() 붙이면 숫자값만 출력

3

In [ ]:
##뺄셈
sub=tf.math.subtract(c1,c2)
sub.numpy()

-1

In [ ]:
##곱셈
mult=tf.math.multiply(c1,c2)
mult.numpy()

2

*vector


In [ ]:
py_list=[10,20,30]
ten_list = tf.constant(py_list,dtype=tf.int32)
ten_list

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30], dtype=int32)>

*행렬정의하기
1.   tf.stack([],[].[]) : 1차 배열위아래쌓기
2. 



In [ ]:
l_a = [1,0]
l_b = [-1.2]
l_c = [1,0]

In [ ]:
l_a = tf.constant(l_a)
l_b = tf.constant(l_b)
l_c = tf.constant(l_c)
A = tf.stack([l_a,l_b,l_c])
A

In [ ]:
l_B = [[10,20],[30,40]]
l_C = [[10,20], [20,40]]

In [ ]:
B = tf.constant(l_B)
C = tf.constant(l_C)
B,C

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 20],
        [30, 40]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 20],
        [20, 40]], dtype=int32)>)

# 고차원텐서
* 1차원배열 1Xm,n개 정의 2차원배열 nXm 정의
* tf.constant([1],[2],,,[1]): 텐서변환
* tf.stack([1],[2],,,[1])
* shape(l,n,m)

In [ ]:
##1차원 배열로 3x2x4 정의하기
l_c1 = [1,2,3,4]
l_c2 = [3,4,2,5]
l_c3 = [2,3,4,5]
l_c4 = [6,5,7,3]
l_c5 = [1,1,1,1,]
l_c6 = [8,1,0,6]

In [ ]:
c1=tf.constant(l_c1)
c2=tf.constant(l_c2)
c3=tf.constant(l_c3)
c4=tf.constant(l_c4)
c5=tf.constant(l_c5)
c6=tf.constant(l_c6)

In [ ]:
X=tf.stack([c1,c2,c3,c4,c5,c6])
X

<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [3, 4, 2, 5],
       [2, 3, 4, 5],
       [6, 5, 7, 3],
       [1, 1, 1, 1],
       [8, 1, 0, 6]], dtype=int32)>

In [ ]:
V=tf.stack([c3,c5])
V

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[2, 3, 4, 5],
       [1, 1, 1, 1]], dtype=int32)>

* 인덱싱

In [ ]:
x=range(1,10)
x=list(x)
x1=tf.constant(x)

In [ ]:
x1

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
x1[2:4]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>

In [ ]:
##3x3 행렬인경우
x2=tf.reshape(x1,[3,-1])
x2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [ ]:
##1행출력
x2[:1]

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>

In [ ]:
##2행출력
x2[:2]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
##1열
x2[:,:1]

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [4],
       [7]], dtype=int32)>

In [ ]:
##2열
x2[:,:2]

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5],
       [7, 8]], dtype=int32)>

*형태변환

In [ ]:
t7=tf.constant(range(0,24))
t7

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23], dtype=int32)>

In [ ]:
r_t7=tf.reshape(t7, [3,8])
r_t7

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]], dtype=int32)>

In [ ]:
r2_t7=tf.reshape(t7, [-1,4])
r2_t7

<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]], dtype=int32)>

In [ ]:
r3_t7=tf.reshape(r2_t7, [-1])
r3_t7

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23], dtype=int32)>

In [ ]:
r4_t7=tf.reshape(r2_t7,[-1,3,4])
r4_t7

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]], dtype=int32)>

In [ ]:
r5_t7 =tf.reshape(r2_t7, [-1,2,4])
r5_t7

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]], dtype=int32)>

In [ ]:
r6_t7 =tf.reshape(r2_t7, [-1,2,2,2])
r6_t7

<tf.Tensor: shape=(3, 2, 2, 2), dtype=int32, numpy=
array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]], dtype=int32)>

In [ ]:
r7_t7 =tf.reshape(r2_t7, [-1,2,2,2])
r7_t7

<tf.Tensor: shape=(3, 2, 2, 2), dtype=int32, numpy=
array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]], dtype=int32)>

*자동미분

In [ ]:
# y = x^2의 미분값 구하기
x = tf.Variable(2.0)

with tf.GradientTape() as tape:
    y=x ** 2
dy_dx = tape.gradient(y,x)
dy_dx.numpy()
     

In [ ]:
##reduced_mean()
m2 = tf.constant([[1.,1.],[2.,2.]])
m2
     

In [4]:

##loss함수 정의
def cal_mse(x,y,a,b):
    y_prde = a * x + b
    squared_error = (y_prde - y) ** 2
    mean_squared_error = tf.reduce_mean(squared_error)

    return mean_squared_error

In [ ]:
a = tf.Variable(0.0)
b = tf.Variable(0.0)

EPOCHS = 1000

for epoch in range(1, EPOCHS+1):
    with tf.GradientTape() as tape:
      mse = cal_mse(x,y,a,b)
    if mse < 0.0000001:
      break
    grade = tape.gradient(mse, {'a':a, 'b':b})
    d_a, d_b = grade['a'],grade['b']
    a.assign_sub(d_a * 0.05) ## a = a - d_a * 0.05(학습률)
    b.assign_sub(d_b * 0.05) ## b = b - d_b * 0.05(학습률)

    if epoch % 20 == 0:
      print("EPOCH %d - MSE : %.4f - a: %.2f - b : %2.2f"%(epoch, mse, a,b))

In [ ]:
y_pred = 2.05 * x -1.54
plt.scatter(x,y)
plt.plot(x,y_pred,color = 'r')
plt.show()

In [ ]:
g = tf.random.Generator.from_seed(2020)
x1 = g.normal(shape=(10,))
noise = np.random.normal(0,1,size = (10,))
y= 3*x-2+noise
     

In [ ]:
y_pred = 1.93 * x1 -1.73
plt.scatter(x1,y)
plt.plot(x1,y_pred,color = 'r')
plt.show()