<a href="https://colab.research.google.com/github/upjun11/r/blob/main/%EA%B9%80%EA%B0%95%EC%9A%B0_%EB%84%98%ED%8C%8C%EC%9D%B4%EC%97%B0%EC%8A%B5%EB%AC%B8%EC%A0%9C_Q.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy 함수

#### 0~1000사이의 값을 25개 저장하고 있는 배열을 생성하세요 (배열1)
* randint 함수를 사용합니다
* 중복 값은 허용합니다.
* seed(777)

In [ ]:
# 코드를 채우세요
import numpy as np
import matplotlib.pyplot as plt
import random

np.random.seed(777)
arr1=np.random.randint(0,1000,25)
arr1

array([103, 815, 571, 934, 599, 945,  71, 669, 639, 116, 423, 985, 814,
       506, 792, 295, 914, 397, 654,  32, 859, 321, 850, 340, 325])

#### Shape 변경

- 배열1의 shape을 변경하여 배열2에 저장하세요. 행은 5개 열은 자동으로 맞추도록 합니다.

In [ ]:
arr2=np.array(arr1).reshape(5,5);
arr2

array([[103, 815, 571, 934, 599],
       [945,  71, 669, 639, 116],
       [423, 985, 814, 506, 792],
       [295, 914, 397, 654,  32],
       [859, 321, 850, 340, 325]])

* arr2의 값 중 71인 값을 찾아 10을 곱하세요

In [ ]:
# 코드를 채우세요
arr2[1:2,1]=arr2[1:2,1]*10
arr2

array([[103, 815, 571, 934, 599],
       [945, 710, 669, 639, 116],
       [423, 985, 814, 506, 792],
       [295, 914, 397, 654,  32],
       [859, 321, 850, 340, 325]])

#### 배열2의 원소 중 가운데 위치한 9개 원소를 추출하여 shape을 유지하여 출력해보세요. (배열3)

In [ ]:
# 코드를 채우세요
arr3=arr2[1:4,1:4]
arr3

array([[710, 669, 639],
       [985, 814, 506],
       [914, 397, 654]])

#### 배열3에 10을 곱한 후 원본 배열(배열2)이 수정됐는지 확인하세요

In [ ]:
# 코드를 채우세요
arr2[1:4,1:4]=arr3*10
arr2

array([[ 103,  815,  571,  934,  599],
       [ 945, 7100, 6690, 6390,  116],
       [ 423, 9850, 8140, 5060,  792],
       [ 295, 9140, 3970, 6540,   32],
       [ 859,  321,  850,  340,  325]])

#### 배열2에서 다시 가운데 9개를 추출한 후 10을 곱하되, 원본 배열(배열2)이 수정되지 않도록 연산하세요 (배열4)

In [ ]:
# 코드를 채우세요
arr2[1:4,1:4]
arr4=arr2[1:4,1:4]
arr4

array([[7100, 6690, 6390],
       [9850, 8140, 5060],
       [9140, 3970, 6540]])

In [ ]:
# 코드를 채우세요
arr4=arr4*10
arr4

array([[71000, 66900, 63900],
       [98500, 81400, 50600],
       [91400, 39700, 65400]])

In [ ]:
arr2

array([[ 103,  815,  571,  934,  599],
       [ 945, 7100, 6690, 6390,  116],
       [ 423, 9850, 8140, 5060,  792],
       [ 295, 9140, 3970, 6540,   32],
       [ 859,  321,  850,  340,  325]])

#### 배열2의 값 중 1000이상인 요소만 선택하여 3행 자동열의 형태로 출력하세요 (배열5)

In [ ]:
# 코드를 채우세요
arr5=arr2[np.where(arr2>1000)]
arr5.reshape(3,3)

array([[7100, 6690, 6390],
       [9850, 8140, 5060],
       [9140, 3970, 6540]])

#### 배열2의 값 중 1000 미만인 요소는 0으로, 1000이상인 요소는 1000으로 변경하여 배열6에 저장하세요

In [ ]:
# 코드를 채우세요
arr6=np.where(arr2>1000,1000,0)
arr6

array([[   0,    0,    0,    0,    0],
       [   0, 1000, 1000, 1000,    0],
       [   0, 1000, 1000, 1000,    0],
       [   0, 1000, 1000, 1000,    0],
       [   0,    0,    0,    0,    0]])

#### 배열6을 1차원 배열로 변환 후 배열7에 저장하세요 (복사)

In [ ]:
arr7 = arr6.flatten()
arr7

array([   0,    0,    0,    0,    0,    0, 1000, 1000, 1000,    0,    0,
       1000, 1000, 1000,    0,    0, 1000, 1000, 1000,    0,    0,    0,
          0,    0,    0])

#### 50~100의 값 범위를 최솟값 50, 최댓값 100인 10개 구간으로 일정하게 나누어 배열8에 저장하되 소숫점 둘째자리까지만 허용합니다

In [ ]:
# 코드를 채우세요
arr8 = np.round(np.linspace(50, 100, 10), 2)
arr8

array([ 50.  ,  55.56,  61.11,  66.67,  72.22,  77.78,  83.33,  88.89,
        94.44, 100.  ])

#### 배열 8의 값을 반올림하여 배열 9에 저장하세요

In [ ]:
# 코드를 채우세요 (np.round함수사용)
arr9=np.round(arr8)
arr9

array([ 50.,  56.,  61.,  67.,  72.,  78.,  83.,  89.,  94., 100.])